# Generated by Django 2.2.4 on 2020-01-06 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('oily', models.IntegerField()),
                ('dry', models.IntegerField()),
                ('sensitive', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('imageId', models.TextField()),
                ('name', models.TextField()),
                ('price', models.IntegerField()),
                ('gender', models.TextField()),
                ('category', models.TextField()),
                ('monthlySales', models.IntegerField()),
                ('ingredients', models.ManyToManyField(to='item.Ingredient')),
            ],
        ),
    ]
