# Generated by Django 2.2.4 on 2020-01-08 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_auto_20200107_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='ingredients',
        ),
        migrations.DeleteModel(
            name='Included',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
