# Generated by Django 2.2.4 on 2020-01-08 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0007_auto_20200108_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='ingredient_ids',
        ),
        migrations.DeleteModel(
            name='Included',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
