# Generated by Django 2.2.4 on 2020-01-08 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0009_auto_20200108_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='imgUrl',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='imageId',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='thumbs',
            name='imgUrl',
            field=models.CharField(max_length=512),
        ),
    ]
