# Generated by Django 2.2.4 on 2020-01-08 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item', '0011_auto_20200109_0130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Included',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('oily', models.IntegerField()),
                ('dry', models.IntegerField()),
                ('sensitive', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('imageId', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('price', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=50)),
                ('ingredients', models.CharField(max_length=512)),
                ('monthlySales', models.IntegerField()),
                ('oily', models.IntegerField()),
                ('dry', models.IntegerField()),
                ('sensitive', models.IntegerField()),
                ('ingredient_ids', models.ManyToManyField(through='item.Included', to='item.Ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='item.Item')),
                ('imgUrl', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Thumbs',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='item.Item')),
                ('imgUrl', models.CharField(max_length=512)),
            ],
        ),
        migrations.AddField(
            model_name='included',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.Ingredient'),
        ),
        migrations.AddField(
            model_name='included',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.Item'),
        ),
    ]
