# Generated by Django 2.2.4 on 2020-01-08 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0012_auto_20200109_0133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='included',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='included',
            name='item',
        ),
        migrations.RemoveField(
            model_name='item',
            name='ingredient_ids',
        ),
        migrations.RemoveField(
            model_name='thumbs',
            name='id',
        ),
        migrations.DeleteModel(
            name='Images',
        ),
        migrations.DeleteModel(
            name='Included',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Thumbs',
        ),
    ]
