# Generated by Django 2.2.4 on 2020-01-09 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0018_auto_20200109_0325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='ingredient_ids',
        ),
        migrations.DeleteModel(
            name='Included',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
